/*
 * Swagger Petstore
 *
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chimera

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type ApiService struct {
	Api
}

func NewApiService() *ApiService {
	return &ApiService{}
}

// Index is the index handler.
func (a *ApiService) Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

// AddPet -
func (a *ApiService) AddPet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeletePet -
func (a *ApiService) DeletePet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindPetById -
func (a *ApiService) FindPetById(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FindPets -
func (a *ApiService) FindPets(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
